### ISSUE TITLE
Diag tool returns 403 when Shield has anonymous_auth and authz_exception: true

### ISSUE THREAD

**Issue by tylerfontaine** [elastic/elasticsearch-support-diagnostics#124]
Currently, the diag tool makes two calls for each API call it makes: One without credentials, which normally return a 401, and after that it retries with credentials.

However, when anonymous auth is enabled in shield, and the authz_exception parameter is set to true, the fist request returns a 403, which does NOT retry with credentials after; rather, it simply fails on the 403. This makes it impossible to run the diags against a cluster with these settings. 

Repro:

Elastic 2.x
Install license, shield

Create an admin user

Set the following in the elasticsearch.yml (note: Example here is file realm, but native would work also)

```
shield.authc:
   realms:
      file1:
        type: file
        order: 0
   anonymous:
      username: anonymous_user
      roles: role1
      authz_exception: true
```

Attempt to run the diag with `-u admin -p` flags

The diag will fail with 403 errors.
